image: node:25-slim

stages:
  - install
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - npm test

build_image:
  stage: build
  image: docker:25
  services:
    - docker:25-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t "$IMAGE_NAME:latest" .
    - docker push "$IMAGE_NAME:latest"

deploy:
  stage: deploy
  image: alpine:3.20
  variables:
    EC2_HOST: 13.212.240.238
    EC2_USER: ec2-user
  before_script:
    - apk add --no-cache openssh-client
    - chmod 600 "$SSH_KEY"
  script:
    - ssh -o StrictHostKeyChecking=no -i "$SSH_KEY" $EC2_USER@$EC2_HOST "
        sudo docker login -u $REGISTRY_USER --password-stdin <<< \"$REGISTRY_PASS\" &&
        sudo docker ps -aq | xargs sudo docker stop | xargs sudo docker rm &&
        sudo docker run -d -p 80:3000 $IMAGE_NAME:latest"