image: node:18

stages:
  - install
  - test
  - deploy

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - npm test

deploy:
  stage: deploy
  when: manual
  script:
    - echo "No deployment configured in this demo"
